"""newupdate

Revision ID: 22c34cfbe211
Revises: 6d64a33b169d
Create Date: 2020-05-27 15:40:57.385706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c34cfbe211'
down_revision = '6d64a33b169d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
