"""update2

Revision ID: 55b3729c6d1c
Revises: 89072e3d859a
Create Date: 2020-05-25 12:23:53.726983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b3729c6d1c'
down_revision = '89072e3d859a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'email')
    op.add_column('voters', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_voters_email'), 'voters', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_email'), table_name='voters')
    op.drop_column('voters', 'email')
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
