"""update22

Revision ID: 6d64a33b169d
Revises: 55b3729c6d1c
Create Date: 2020-05-25 12:25:29.427601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d64a33b169d'
down_revision = '55b3729c6d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_voters_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voters_email'))
        batch_op.drop_column('email')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
