"""onupdate

Revision ID: 845109c29432
Revises: 406878e98cdb
Create Date: 2020-06-29 19:40:44.575152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845109c29432'
down_revision = '406878e98cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_otps_voter_id_voters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_otps_voter_id_voters'), 'voters', ['voter_id'], ['id'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_otps_voter_id_voters'), type_='foreignkey')
        batch_op.create_foreign_key('fk_otps_voter_id_voters', 'voters', ['voter_id'], ['id'])

    # ### end Alembic commands ###
