"""update

Revision ID: 89072e3d859a
Revises: 
Create Date: 2020-05-25 12:15:22.366148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89072e3d859a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_email', table_name='candidates')
    op.drop_column('candidates', 'email')
    op.add_column('voters', sa.Column('email', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_voters_email'), 'voters', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_email'), table_name='voters')
    op.drop_column('voters', 'email')
    op.add_column('candidates', sa.Column('email', sa.VARCHAR(length=100), nullable=True))
    op.create_index('ix_candidates_email', 'candidates', ['email'], unique=1)
    # ### end Alembic commands ###
