"""update7

Revision ID: a44d92f0bffa
Revises: 22c34cfbe211
Create Date: 2020-05-28 10:25:36.981127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a44d92f0bffa'
down_revision = '22c34cfbe211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp_fname', sa.String(length=180), nullable=True))
        batch_op.drop_column('dp_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dp_name', sa.VARCHAR(length=30), nullable=True))
        batch_op.drop_column('dp_fname')

    # ### end Alembic commands ###
