"""db_new

Revision ID: bd81130bcc5a
Revises: e02e4e0c1124
Create Date: 2020-06-30 11:52:17.898629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd81130bcc5a'
down_revision = 'e02e4e0c1124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidates_id_number_voters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidates_id_number_voters'), 'voters', ['id_number'], ['id_number'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('gen_passkeys', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gen_passkeys_id_number_voters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_gen_passkeys_id_number_voters'), 'voters', ['id_number'], ['id_number'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_payment_by_candidates', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_payments_payment_by_candidates'), 'candidates', ['payment_by'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reg_end', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('reg_start', sa.String(length=40), nullable=True))

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_votes_vote_post_posts', type_='foreignkey')
        batch_op.drop_constraint('fk_votes_vote_ref_vrns', type_='foreignkey')
        batch_op.drop_constraint('fk_votes_vote_for_candidates', type_='foreignkey')
        batch_op.drop_constraint('fk_votes_vote_by_voters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_votes_vote_post_posts'), 'posts', ['vote_post'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_votes_vote_by_voters'), 'voters', ['vote_by'], ['id_number'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_votes_vote_for_candidates'), 'candidates', ['vote_for'], ['id_number'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_votes_vote_ref_vrns'), 'vrns', ['vote_ref'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_votes_vote_ref_vrns'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_votes_vote_for_candidates'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_votes_vote_by_voters'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_votes_vote_post_posts'), type_='foreignkey')
        batch_op.create_foreign_key('fk_votes_vote_by_voters', 'voters', ['vote_by'], ['id_number'])
        batch_op.create_foreign_key('fk_votes_vote_for_candidates', 'candidates', ['vote_for'], ['id_number'])
        batch_op.create_foreign_key('fk_votes_vote_ref_vrns', 'vrns', ['vote_ref'], ['id'])
        batch_op.create_foreign_key('fk_votes_vote_post_posts', 'posts', ['vote_post'], ['id'])

    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('reg_start')
        batch_op.drop_column('reg_end')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_payment_by_candidates'), type_='foreignkey')
        batch_op.create_foreign_key('fk_payments_payment_by_candidates', 'candidates', ['payment_by'], ['id'])

    with op.batch_alter_table('gen_passkeys', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_gen_passkeys_id_number_voters'), type_='foreignkey')
        batch_op.create_foreign_key('fk_gen_passkeys_id_number_voters', 'voters', ['id_number'], ['id_number'])

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_candidates_id_number_voters'), type_='foreignkey')
        batch_op.create_foreign_key('fk_candidates_id_number_voters', 'voters', ['id_number'], ['id_number'], onupdate='CASCADE')

    # ### end Alembic commands ###
