"""onupdate2

Revision ID: e02e4e0c1124
Revises: 845109c29432
Create Date: 2020-06-29 19:48:03.079233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02e4e0c1124'
down_revision = '845109c29432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_candidates_id_number_voters', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidates_id_number_voters'), 'voters', ['id_number'], ['id_number'], onupdate='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_candidates_id_number_voters'), type_='foreignkey')
        batch_op.create_foreign_key('fk_candidates_id_number_voters', 'voters', ['id_number'], ['id_number'])

    # ### end Alembic commands ###
